CREATE TABLE MataKuliah(
	IDMK VARCHAR(5),
	NamaMK VARCHAR(40),
	SKS INT,
	PRIMARY KEY(IDMK)
)

CREATE TABLE AuditMK(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDMK VARCHAR(5),
	SKS_New INT,
	SKS_Old INT,
	NamaMK_New VARCHAR(40),
	NamaMK_Old VARCHAR(40),
	Date DATE,
	users VARCHAR(40),
	FOREIGN KEY(IDMK) REFERENCES MataKuliah(IDMK)
)
