CREATE TRIGGER MenentukanSKS 
ON MataKuliah
AFTER INSERT
AS
BEGIN
    DECLARE @SKS INT;
    DECLARE @IDMK VARCHAR(5);

    SELECT @SKS = CAST(SUBSTRING(INSERTED.IDMK, 3, 1) AS INT),
           @IDMK = INSERTED.IDMK
    FROM INSERTED;

    UPDATE MataKuliah
    SET SKS = @SKS
    WHERE IDMK = @IDMK;
END;
GO